config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('message/', include('message.urls', namespace='message')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

message/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from message.apps import MessageConfig
from message.services import to_run_mail
from message.views import (
    ClientListView,
    ClientDetailView,
    ClientCreateView,
    ClientUpdateView,
    ClientDeleteView,
    SmsListView,
    SmsDetailView,
    SmsCreateView,
    SmsUpdateView,
    SmsDeleteView,
    MailListView,
    MailDetailView,
    MailCreateView,
    MailUpdateView,
    MailDeleteView,
    MainView,
    Contacts,
    Message, SendListView, SendCreateView,
)


app_name = MessageConfig.name

urlpatterns = [
    # path('', base, name='base.html'),
    path("", MainView.as_view(), name="main"),
    path("contacts/", Contacts.as_view(), name="contacts"),
    path("message/", Message.as_view(), name="message"),

    path("client/", cache_page(60)(ClientListView.as_view()), name="client_list"),
    path("client/<int:pk>/", ClientDetailView.as_view(), name="client_detail"),
    path("client/create/", ClientCreateView.as_view(), name="client_create"),
    path("client/<int:pk>/update/", ClientUpdateView.as_view(), name="client_update"),
    path("client/<int:pk>/delete/", ClientDeleteView.as_view(), name="client_delete"),

    path("sms/list/", SmsListView.as_view(), name="sms_list"),
    path("sms/<int:pk>/", SmsDetailView.as_view(), name="sms_detail"),
    path("sms/create/", SmsCreateView.as_view(), name="sms_create"),
    path("sms/<int:pk>/update/", SmsUpdateView.as_view(), name="sms_update"),
    path("sms/<int:pk>/delete/", SmsDeleteView.as_view(), name="sms_delete"),

    path("mail/list/", MailListView.as_view(), name="mail_list"),
    path("mail/<int:pk>/", MailDetailView.as_view(), name="mail_detail"),
    path("mail/create/", MailCreateView.as_view(), name="mail_create"),
    path("mail/<int:pk>/update/", MailUpdateView.as_view(), name="mail_update"),
    path("mail/<int:pk>/delete/", MailDeleteView.as_view(), name="mail_delete"),
    path("mail/<int:pk>/to_run_mail/", to_run_mail, name="send_mail"),

    path("send/", cache_page(60)(SendListView.as_view()), name="send_list"),
    path("send/create/", SendCreateView.as_view(), name="send_create"),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import (
    UserCreateView,
    email_verification,
    UserForgotPasswordView,
    UserPasswordResetConfirmView, UserDeleteView, UserUpdateView, UserDetailView, UserListView,
)

app_name = UsersConfig.name

urlpatterns = [
    path("login/", LoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", UserCreateView.as_view(), name="register"),

    path("email-confirm/<str:token>/", email_verification, name="email-confirm"),
    path("password-reset/", UserForgotPasswordView.as_view(), name="password_reset"),
    path(
        "set-new-password/<uidb64>/<token>/",
        UserPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path("users/", UserListView.as_view(), name="user_list"),
    path("detail/<int:pk>/", UserDetailView.as_view(), name="user_detail"),
    path("update/<int:pk>/", UserUpdateView.as_view(), name="user_update"),
    path("delete/<int:pk>/", UserDeleteView.as_view(), name="user_delete"),
]

message/forms.py
from django.forms import ModelForm

from message.models import Client, Sms, Mail, Send


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"


class ClientForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Client
        fields = "__all__"
        exclude = ("can_blocking_client", "owner")


class SmsForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Sms
        fields = "__all__"
        exclude = ("can_blocking_sms", "owner")


class MailForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Mail
        fields = "__all__"
        exclude = ("set_is_active", "owner")


class SendForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Send
        fields = "__all__"


class ClientModeratorForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Client
        fields = "__all__"
        exclude = ["can_blocking_client",]


class SmsModeratorForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Client
        fields = "__all__"
        exclude = ["can_blocking_sms",]


class MailModeratorForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Client
        fields = "__all__"
        exclude = ["set_is_active",]


class SendModeratorForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Send
        fields = "__all__"

message/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy


from message.forms import (
    ClientForm,
    SmsForm,
    MailForm,
    ClientModeratorForm,
    SmsModeratorForm,
    MailModeratorForm, SendForm,
)
from message.models import Client, Sms, Mail, Send
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
    TemplateView,
)

from message.services import get_clients_from_cash, get_send_from_cash


def base(request):
    """Основной шаблон"""
    return render(request, "base.html")


class Contacts(TemplateView):
    """Шаблон контакты"""

    template_name = "message/contacts.html"

    def contacts(request):
        if request.method == "POST":
            name = request.POST.get("name")  # получаем имя
            message = request.POST.get("message")  # получаем сообщение
            return HttpResponse(f"Спасибо, {name}! {message} Сообщение получено.")
        return render(request, "message/contacts.html")


class Message(TemplateView):
    """Страница ответа на отправленное сообщение"""

    template_name = "message/message.html"


class MainView(TemplateView):
    """Главная страница"""

    template_name = "message/main.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["mail_count"] = len(Mail.objects.all())
        context["active_count"] = len(Mail.objects.filter(status="Запущен"))
        context["unique_email"] = len(Client.objects.all())
        return context


class ClientListView(ListView):
    """Получатели рассылок - просмотр"""

    model = Client

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user == self.object.owner:
            self.object.save()
            return self.object
        raise PermissionDenied

    def get_queryset(self):
        return get_clients_from_cash()
# app_name/<model_name>_<action> т.е будет message/client_list.html


class ClientDetailView(DetailView, LoginRequiredMixin):
    """Получатель рассылки"""

    model = Client
    form_class = ClientForm

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user == self.object.owner:
            self.object.save()
            return self.object
        raise PermissionDenied


class ClientCreateView(CreateView, LoginRequiredMixin):
    """Получатель рассылки - создание"""

    model = Client
    form_class = ClientForm
    success_url = reverse_lazy("message:client_list")

    def form_valid(self, form):
        client = form.save()
        user = self.request.user
        client.owner = user
        client.save()

        return super().form_valid(form)


class ClientUpdateView(UpdateView, LoginRequiredMixin):
    """Получатель рассылки - обновление"""

    model = Client
    form_class = ClientForm
    success_url = reverse_lazy("message:client_list")

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user == self.object.owner:
            self.object.save()
            return self.object
        raise PermissionDenied

    def get_form_class(self):
        user = self.request.user
        if user.has_perm("message.can_unblocking_client") and user.has_perm(
            "message.can_disabling_mailings"
        ):
            return ClientModeratorForm
        return ClientForm


class ClientDeleteView(DeleteView):
    """Получатель рассылки - удаление"""

    model = Client
    success_url = reverse_lazy("message:client_list")

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user == self.object.owner:
            self.object.save()
            return self.object
        raise PermissionDenied


class SmsListView(ListView):
    """Сообщения - просмотр"""

    model = Sms


class SmsDetailView(DetailView, LoginRequiredMixin):
    """Просмотр выбранного сообщения"""

    model = Sms

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user == self.object.owner:
            self.object.save()
            return self.object
        raise PermissionDenied


class SmsCreateView(CreateView, LoginRequiredMixin):
    """Сообщения - создание"""

    model = Sms
    form_class = SmsForm
    success_url = reverse_lazy("message:sms_list")

    def form_valid(self, form):
        sms = form.save()
        user = self.request.user
        sms.owner = user
        sms.save()

        return super().form_valid(form)


class SmsUpdateView(UpdateView, LoginRequiredMixin):
    """Сообщения - обновление"""

    model = Sms
    form_class = SmsForm
    success_url = reverse_lazy("message:sms_list")

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user == self.object.owner:
            self.object.save()
            return self.object
        raise PermissionDenied

    def get_form_class(self):
        user = self.request.user
        if user.has_perm("message.can_unblocking_sms") and user.has_perm(
            "message.can_disabling_mailings"
        ):
            return SmsModeratorForm
        return SmsForm


class SmsDeleteView(DeleteView):
    """Сообщения - удаление"""

    model = Sms
    success_url = reverse_lazy("message:sms_list")

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user == self.object.owner:
            self.object.save()
            return self.object
        raise PermissionDenied


class MailListView(ListView):
    """Рассылка - просмотр"""

    model = Mail


class MailDetailView(DetailView, LoginRequiredMixin):
    """Просмотр выбранной рассылки"""

    model = Mail

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user == self.object.owner:
            self.object.save()
            return self.object
        raise PermissionDenied


class MailCreateView(CreateView, LoginRequiredMixin):
    """Рассылка - создание"""

    model = Mail
    form_class = MailForm
    success_url = reverse_lazy("message:mail_list")

    def form_valid(self, form):
        mail = form.save()
        user = self.request.user
        mail.owner = user
        mail.save()


class MailUpdateView(UpdateView, LoginRequiredMixin):
    """Рассылка - обновление"""

    model = Mail
    form_class = MailForm
    success_url = reverse_lazy("message:mail_list")

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user == self.object.owner:
            self.object.save()
            return self.object
        raise PermissionDenied

    def get_form_class(self):
        user = self.request.user
        if user.has_perm("message.can_unblocking_mailing") and user.has_perm(
            "message.can_disabling_mailings"
        ):
            return MailModeratorForm
        return MailForm


class MailDeleteView(DeleteView):
    """Рассылка - удаление"""

    model = Mail
    success_url = reverse_lazy("message:mail_list")

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user == self.object.owner:
            self.object.save()
            return self.object
        raise PermissionDenied


class SendListView(ListView, LoginRequiredMixin):
    model = Send

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user == self.object.owner:
            self.object.save()
            return self.object
        raise PermissionDenied

    def get_queryset(self):
        return get_send_from_cash()


class SendCreateView(LoginRequiredMixin, CreateView):
    model = Send
    form_class = SendForm

    def form_valid(self, form):
        send = form.save()
        user = self.request.user
        send.owner = user
        send.save()

message/templates/message/includes/ink_info.html
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
  <meta name="generator" content="Hugo 0.122.0">
  <title>Сервис управления рассылками, администрирования и получения статистики</title>

  <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/sticky-footer-navbar/">



  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">

<link href="/static/css/bootstrap.min.css" rel="stylesheet">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.3/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.3/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.3/assets/img/favicons/safari-pinned-tab.svg" color="#712cf9">
<link rel="icon" href="/docs/5.3/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#712cf9">

<style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }

      .btn-bd-primary {
        --bd-violet-bg: #712cf9;
        --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

        --bs-btn-font-weight: 600;
        --bs-btn-color: var(--bs-white);
        --bs-btn-bg: var(--bd-violet-bg);
        --bs-btn-border-color: var(--bd-violet-bg);
        --bs-btn-hover-color: var(--bs-white);
        --bs-btn-hover-bg: #6528e0;
        --bs-btn-hover-border-color: #6528e0;
        --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
        --bs-btn-active-color: var(--bs-btn-hover-color);
        --bs-btn-active-bg: #5a23c8;
        --bs-btn-active-border-color: #5a23c8;
      }

      .bd-mode-toggle {
        z-index: 1500;
      }

      .bd-mode-toggle .dropdown-menu .active .bi {
        display: block !important;
      }
</style>
<!-- Custom styles for this template -->
<link href="sticky-footer-navbar.css" rel="stylesheet">
</head>
  <body class="d-flex flex-column h-100">
  <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
    <symbol id="check2" viewBox="0 0 16 16">
      <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
    </symbol>
    <symbol id="circle-half" viewBox="0 0 16 16">
      <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
    </symbol>
    <symbol id="moon-stars-fill" viewBox="0 0 16 16">
      <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
      <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
    </symbol>
    <symbol id="sun-fill" viewBox="0 0 16 16">
      <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
    </symbol>
  </svg>

  <div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
    <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
            id="bd-theme"
            type="button"
            aria-expanded="false"
            data-bs-toggle="dropdown"
            aria-label="Toggle theme (auto)">
      <svg class="bi my-1 theme-icon-active" width="1em" height="1em"><use href="#circle-half"></use></svg>
      <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
    </button>
    <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
      <li>
        <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light" aria-pressed="false">
          <svg class="bi me-2 opacity-50" width="1em" height="1em"><use href="#sun-fill"></use></svg>
          Light
          <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
        </button>
      </li>
      <li>
        <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark" aria-pressed="false">
          <svg class="bi me-2 opacity-50" width="1em" height="1em"><use href="#moon-stars-fill"></use></svg>
          Dark
          <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
        </button>
      </li>
      <li>
        <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto" aria-pressed="true">
          <svg class="bi me-2 opacity-50" width="1em" height="1em"><use href="#circle-half"></use></svg>
          Auto
          <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
        </button>
      </li>
    </ul>
  </div>
  <header>
    <!-- Fixed navbar -->
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav me-auto mb-2 mb-md-0">
            {% if user.is_authenticated %}
              <li class="nav-item"><a class="nav-link" href="{% url 'users:logout' %}">Пользователь: {{user.email}}</a></li>
              <li class="nav-item"><a class="nav-link" href="{% url 'users:logout' %}">Выход</a></li>
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
              <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'message:main' %}">На главную</a></li>
              <li class="nav-item"><a class="nav-link" href="{% url 'message:client_list' %}">Клиенты</a></li>
              <li class="nav-item"><a class="nav-link" href="{% url 'message:sms_list' %}" aria-disabled="true">Сообщения</a></li>
              <li class="nav-item"><a class="nav-link" href="{% url 'message:mail_list' %}" aria-disabled="true">Рассылки</a></li>
              <li class="nav-item"><a class="nav-link" href="{% url 'users:user_list' %}" aria-disabled="true">Пользователи</a></li>
              <li class="nav-item"><a class="nav-link" href="{% url 'message:send_list' %}" aria-disabled="true">Попытка рассылки</a></li>
              <li class="nav-item"><a class="nav-link" href="{% url 'message:contacts' %}" aria-disabled="true">Контакты</a></li>
            </ul>
              {% else %}
              <li class="nav-item"><a class="nav-link" href="{% url 'users:login' %}">Вход</a></li>
              <li class="nav-item"><a class="nav-link" href="{% url 'users:register' %}">Регистрация</a></li>
              <li class="nav-item"><a class="nav-link" href="{% url 'message:contacts' %}" aria-disabled="true">Контакты</a></li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
  </header>

message/templates/message/includes/ink_up.html
<div class="container">
    <div class="row mb-2">
        <div class="col-md-12">
            <p class="mb-0">
                <a class="btn btn-dark" href="#" role="button">Наверх</a>
            </p>
        </div>
    </div>
</div>