config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('message/', include('message.urls', namespace='message')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import (
    UserCreateView,
    email_verification,
    UserForgotPasswordView,
    UserPasswordResetConfirmView, UserDeleteView, UserUpdateView, UserDetailView, UserListView,
)

app_name = UsersConfig.name

urlpatterns = [
    path("login/", LoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", UserCreateView.as_view(), name="register"),

    path("email-confirm/<str:token>/", email_verification, name="email-confirm"),
    path("password-reset/", UserForgotPasswordView.as_view(), name="password_reset"),
    path(
        "set-new-password/<uidb64>/<token>/",
        UserPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path("users/", UserListView.as_view(), name="user_list"),
    path("detail/<int:pk>/", UserDetailView.as_view(), name="user_detail"),
    path("update/<int:pk>/", UserUpdateView.as_view(), name="user_update"),
    path("delete/<int:pk>/", UserDeleteView.as_view(), name="user_delete"),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name="email")
    first_name = models.CharField(max_length=50, verbose_name="Имя")
    last_name = models.CharField(max_length=50, verbose_name="Фамилия")
    phone = models.CharField(
        max_length=35,
        verbose_name="телефон",
        blank=True,
        null=True,
        help_text="Введите номер телефона",
    )
    country = models.CharField(
        max_length=50, verbose_name="country", blank=True, null=True
    )
    avatar = models.ImageField(
        upload_to="users/avatars/",
        verbose_name="аватар",
        blank=True,
        null=True,
        help_text="Загрузите аватар",
    )

    token = models.CharField(
        max_length=100, verbose_name="token", blank=True, null=True
    )

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"
        permissions = [
            ("can_block_user", "can block user"),
        ]

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.forms import PasswordResetForm, SetPasswordForm
from django.forms import ModelForm
from django.urls import reverse_lazy

from message.forms import StyleFormMixin
from users.models import User


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    """Форма регистрации пользователя"""
    class Meta:
        model = User
        fields = ("email", "password1", "password2")


class UserForm(StyleFormMixin, UserChangeForm):
    """Форма данных пользователя"""
    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "email",
            "password",
            "phone",
            "avatar",
            "country",
        )


class UserUpdateForm(StyleFormMixin, ModelForm):
    """Форма обновления данных пользователя"""
    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "email",
            "password",
            "phone",
            "avatar",
            "country",
        )
        success_url = reverse_lazy("users:user_list")


class UserForgotPasswordForm(PasswordResetForm):
    """Форма запроса на восстановление пароля"""

    def __init__(self, *args, **kwargs):
        """Обновление стилей формы"""
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update(
                {"class": "form-control", "autocomplete": "off"}
            )


class UserSetNewPasswordForm(SetPasswordForm):
    """Форма изменения пароля пользователя после подтверждения"""

    def __init__(self, *args, **kwargs):
        """Обновление стилей формы"""
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update(
                {"class": "form-control", "autocomplete": "off"}
            )

users/views.py
import secrets

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import PasswordResetView, PasswordResetConfirmView
from django.contrib.messages.views import SuccessMessageMixin
from django.core.exceptions import PermissionDenied
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from config.settings import EMAIL_HOST_USER
from users.forms import UserRegisterForm, UserForgotPasswordForm, UserSetNewPasswordForm, UserForm, UserUpdateForm
from users.models import User


class UserCreateView(CreateView):
    """Переход после регистрации на страницу пользователя"""

    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy("users:login")

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        user.token = token
        user.save()
        host = self.request.get_host()
        url = f"http://{host}/users/email-confirm/{token}/"
        send_mail(
            subject="Подтверждение почты",
            message=f"Привет! Для подтверждения почты перейдите по ссылке {url}",
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email],
        )
        return super().form_valid(form)


def email_verification(request, token):
    """Подтверждение email"""
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse("users:login"))


class UserForgotPasswordView(SuccessMessageMixin, PasswordResetView):
    """Представление по сбросу пароля по почте"""

    form_class = UserForgotPasswordForm
    template_name = "users/user_password_reset.html"
    success_url = reverse_lazy("users:login")
    success_message = (
        "Письмо с инструкцией по восстановлению пароля отправлено на ваш email"
    )
    subject_template_name = "users/email/password_subject_reset_mail.txt"
    email_template_name = "users/email/password_reset_mail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Запрос на восстановление пароля"
        return context


class UserPasswordResetConfirmView(SuccessMessageMixin, PasswordResetConfirmView):
    """Представление установки нового пароля"""

    form_class = UserSetNewPasswordForm
    template_name = "users/user_password_set_new.html"
    success_url = reverse_lazy("users:login")
    success_message = "Пароль успешно изменен. Можете авторизоваться на сайте."

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Установить новый пароль"
        return context


class UserListView(ListView, LoginRequiredMixin):
    """Страница пользователей"""

    model = User
    template_name = "users/user_list.html"


class UserDetailView(DetailView, LoginRequiredMixin):
    """Просмотр пользователя"""

    model = User
    form_class = UserUpdateForm

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user.is_superuser:
            return self.object
        raise PermissionDenied


class UserUpdateView(UpdateView, LoginRequiredMixin):
    """Пользователь - обновление"""

    model = User
    form_class = UserUpdateForm
    success_url = reverse_lazy("users:user_list")

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user.is_superuser:
            return self.object
        raise PermissionDenied


class UserDeleteView(DeleteView):
    """Пользователь - удаление"""

    model = User
    success_url = reverse_lazy("users:user_list")

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user.is_superuser:
            return self.object
        raise PermissionDenied

users/templates/users/user_confirm_delete.html
{% extends 'message/base.html' %}

{% block content %}
<main class="flex-shrink-0">
  <div class="container">
    <h1 class="mt-5">Удаление пользователя</h1>
    <p class="lead"></p>
    <div class="row mb-2">
    <div class="col-md-12">
        <div class="container">
    <div class="row">
        <div class="col">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <p class="card-text">Вы действительно хотите удалить пользователя: "{{object.email}}"</p>
                    <div class="card-body">
                        {%  csrf_token %}
                    </div>
                    <div class="row mb-2">
                    <div class="col-md-12">
                        <button type="submit" class="btn btn-dark">Удалить</button>
                        <a class="btn btn-dark" href="{% url 'users:user_list' %}" role="button">Отменить</a>
                    </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
    </div>
    </div>
  </div>
</main>
{% endblock %}

users/templates/users/user_detail.html
{% extends 'message/base.html' %}

{% block content %}
<main class="flex-shrink-0">
  <div class="container">
    <h1 class="mt-5">Пользователь</h1>
    <p class="lead"></p>
    <div class="row mb-2">
    <div class="col-md-12">
      <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <strong class="d-inline-block mb-2 text-primary-emphasis">email: {{object.email}}</strong>
          <strong class="d-inline-block mb-2 text-primary-emphasis">Имя: {{object.first_name}}</strong>
          <strong class="d-inline-block mb-2 text-primary-emphasis">Фамилия: {{object.last_name}}</strong>
          <strong class="d-inline-block mb-2 text-primary-emphasis">Телефон: {{object.phone}}</strong>
          <strong class="d-inline-block mb-2 text-primary-emphasis">Страна: {{object.country}}</strong>
          <avatar class="d-inline-block mb-2 text-primary-emphasis">Аватар: {{object.country}}</avatar>

        </div>
        <div class="row mb-2">
        <div class="col-md-12">
          <a class="btn btn-dark" href="{% url 'users:user_list' %}" role="button">Назад</a>
        </div>
        </div>
      </div>
    </div>
    </div>
  </div>
</main>
{% endblock %}

users/templates/users/user_form.html
{% extends 'message/base.html' %}

{% block content %}
<main class="flex-shrink-0">
  <div class="container">
    <h1 class="mt-5">Регистрация нового пользователя</h1>
    <p class="lead"></p>
    <div class="row mb-2">
    <div class="col-md-12">
    <div class="container">
        <div class="row">
            <div class="col">
                <form class="row" method="post" enctype="multipart/form-data">
                    <div class="card">
                        <div class="card-body">
                            {%  csrf_token %}
                            {{ form.as_p }}
                        </div>
                        <div class="row mb-2">
                        <div class="col-md-12">
                            <button type="submit" class="btn btn-dark">Зарегистрироваться</button>
                        </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    </div>
    </div>
  </div>
</main>
{% endblock %}

users/templates/users/user_list.html
{% extends 'message/base.html' %}

{% block content %}
<main class="flex-shrink-0">
  <div class="container">
    <h1 class="mt-5">Пользователи</h1>
    <div class="container">
    <div class="row mb-2">
    <div class="col-md-12">
    {% for object in object_list %}
      <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <strong class="d-inline-block mb-2 text-primary-emphasis">email: {{object.email}}</strong>
          <strong class="d-inline-block mb-2 text-primary-emphasis">Имя: {{object.first_name}}</strong>
          <strong class="d-inline-block mb-2 text-primary-emphasis">Фамилия: {{object.last_name}}</strong>
          <strong class="d-inline-block mb-2 text-primary-emphasis">Активность: {{ object.is_active |yesno:"Активна, Не активна" }}</strong>
          <strong class="d-inline-block mb-2 text-primary-emphasis">Телефон: {{object.phone}}</strong>
          <strong class="d-inline-block mb-2 text-primary-emphasis">Страна: {{object.country}}</strong>
          <strong class="d-inline-block mb-2 text-primary-emphasis">Аватар: {{object.country}}</strong>
        </div>

        <div class="row mb-2">
        <div class="col-md-12">
        {% if user.is_superuser %}
          <a class="btn btn-dark" href="{% url 'users:user_update' object.pk %}" role="button">Редактировать</a>
          <a class="btn btn-dark" href="{% url 'users:user_delete' object.pk %}" role="button">Удалить</a>
        {% endif %}
        </div>
        </div>
      </div>
    {% endfor %}
    </div>
    </div>
    </div>
  </div>
</main>
{% endblock %}

users/templates/users/user_password_reset.html
{% extends 'message/base.html' %}

{% block content %}
<main class="flex-shrink-0">
  <div class="container">
    <h1 class="mt-5">Запрос на восстановление пароля на сайте</h1>
    <p class="lead"></p>
    <div class="row mb-2">
    <div class="col-md-12">
    <div class="container">
        <div class="row">
            <div class="col">
                <form class="row" method="post" enctype="multipart/form-data">
                    <div class="card">
                        <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}
                        </div>
                        <div class="row mb-2">
                        <div class="col-md-12">
                            <button type="submit" class="btn btn-dark">Восстановить пароль</button>
                        </div>
                        </div>
                        <div class="row mb-2">
                        <div class="col-md-12">
                            <a class="btn btn-dark" href="{% url 'users:login' %}" role="button">Назад</a>
                        </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    </div>
    </div>
  </div>
</main>
{% endblock %}

users/templates/users/user_password_set_new.html
{% extends 'message/base.html' %}

{% block content %}
<main class="flex-shrink-0">
  <div class="container">
    <h1 class="mt-5">Установить новый пароль</h1>
    <p class="lead"></p>
    <div class="row mb-2">
    <div class="col-md-12">
    <div class="container">
        <div class="row">
            <div class="col">
                <form class="row" method="post" enctype="multipart/form-data">
                    <div class="card">
                        <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}
                        </div>
                        <div class="row mb-2">
                        <div class="col-md-12">
                            <button type="submit" class="btn btn-dark">Подтвердить</button>
                        </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    </div>
    </div>
  </div>
</main>
{% endblock %}