config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('message/', include('message.urls', namespace='message')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

message/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from message.apps import MessageConfig
from message.services import to_run_mail
from message.views import (
    ClientListView,
    ClientDetailView,
    ClientCreateView,
    ClientUpdateView,
    ClientDeleteView,
    SmsListView,
    SmsDetailView,
    SmsCreateView,
    SmsUpdateView,
    SmsDeleteView,
    MailListView,
    MailDetailView,
    MailCreateView,
    MailUpdateView,
    MailDeleteView,
    MainView,
    Contacts,
    Message, SendListView, SendCreateView,
)


app_name = MessageConfig.name

urlpatterns = [
    # path('', base, name='base.html'),
    path("", MainView.as_view(), name="main"),
    path("contacts/", Contacts.as_view(), name="contacts"),
    path("message/", Message.as_view(), name="message"),

    path("client/", cache_page(60)(ClientListView.as_view()), name="client_list"),
    path("client/<int:pk>/", ClientDetailView.as_view(), name="client_detail"),
    path("client/create/", ClientCreateView.as_view(), name="client_create"),
    path("client/<int:pk>/update/", ClientUpdateView.as_view(), name="client_update"),
    path("client/<int:pk>/delete/", ClientDeleteView.as_view(), name="client_delete"),

    path("sms/list/", SmsListView.as_view(), name="sms_list"),
    path("sms/<int:pk>/", SmsDetailView.as_view(), name="sms_detail"),
    path("sms/create/", SmsCreateView.as_view(), name="sms_create"),
    path("sms/<int:pk>/update/", SmsUpdateView.as_view(), name="sms_update"),
    path("sms/<int:pk>/delete/", SmsDeleteView.as_view(), name="sms_delete"),

    path("mail/list/", MailListView.as_view(), name="mail_list"),
    path("mail/<int:pk>/", MailDetailView.as_view(), name="mail_detail"),
    path("mail/create/", MailCreateView.as_view(), name="mail_create"),
    path("mail/<int:pk>/update/", MailUpdateView.as_view(), name="mail_update"),
    path("mail/<int:pk>/delete/", MailDeleteView.as_view(), name="mail_delete"),
    path("mail/<int:pk>/to_run_mail/", to_run_mail, name="send_mail"),

    path("send/", cache_page(60)(SendListView.as_view()), name="send_list"),
    path("send/create/", SendCreateView.as_view(), name="send_create"),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import (
    UserCreateView,
    email_verification,
    UserForgotPasswordView,
    UserPasswordResetConfirmView, UserDeleteView, UserUpdateView, UserDetailView, UserListView,
)

app_name = UsersConfig.name

urlpatterns = [
    path("login/", LoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", UserCreateView.as_view(), name="register"),

    path("email-confirm/<str:token>/", email_verification, name="email-confirm"),
    path("password-reset/", UserForgotPasswordView.as_view(), name="password_reset"),
    path(
        "set-new-password/<uidb64>/<token>/",
        UserPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path("users/", UserListView.as_view(), name="user_list"),
    path("detail/<int:pk>/", UserDetailView.as_view(), name="user_detail"),
    path("update/<int:pk>/", UserUpdateView.as_view(), name="user_update"),
    path("delete/<int:pk>/", UserDeleteView.as_view(), name="user_delete"),
]

message/models.py
from django.db import models

from users.models import User


class Client(models.Model):
    """Получатель рассылки"""

    email = models.EmailField(
        unique=True, verbose_name="e-mail", help_text="Введите e-mail"
    )  # Email (строка, уникальное)
    name = models.CharField(
        max_length=100, verbose_name="ФИО", help_text="Укажите ФИО"
    )  # Ф.И.О. (строка)
    comment = models.TextField(
        null=True,
        blank=True,
        verbose_name="комментарий",
        help_text="Добавьте комментарий",
    )  # Комментарий (текст)
    is_active = models.BooleanField(default=True, verbose_name="активность")
    owner = models.ForeignKey(
        User,
        verbose_name="Получатель",
        help_text="укажите получателя рассылки",
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Получатель"
        verbose_name_plural = "Получатели"
        ordering = [
            "name",
        ]
        permissions = [
            ('can_blocking_client', 'Может блокировать получателя'),
        ]


class Sms(models.Model):
    """Сообщение"""

    topic = models.CharField(
        max_length=100, verbose_name="Тема", help_text="Укажите тему письма"
    )  # Тема письма (строка)
    content = models.TextField(
        null=True,
        blank=True,
        verbose_name="Содержание",
        help_text="Добавьте содержание",
    )  # Тело письма (текст)
    is_active = models.BooleanField(default=True, verbose_name="активность")
    owner = models.ForeignKey(
        User,
        verbose_name="Владелец сообщения",
        help_text="укажите Владельца сообщения",
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
    )

    def __str__(self):
        return self.topic

    class Meta:
        verbose_name = "Сообщение"
        verbose_name_plural = "Сообщения"
        permissions = [
            ('can_blocking_sms', 'Может блокировать сообщение'),
        ]


class Mail(models.Model):
    """Рассылка"""

    STATUS_COMPETED = "Завершен"
    STATUS_CREATED = "Создан"
    STATUS_LAUNCHED = "Запущен"

    STATUS_CHOICES = [
        (STATUS_COMPETED, "статус: Завершен"),
        (STATUS_CREATED, "статус: Создан"),
        (STATUS_LAUNCHED, "статус: Запущен"),
    ]

    first_dispatch = models.DateTimeField(
        auto_now_add=True, verbose_name="Дата первой отправки"
    )  # Дата и время первой отправки
    end_sending = models.DateTimeField(
        auto_now_add=True, verbose_name="Дата окончания отправки"
    )  # Дата и время окончания отправки
    status = models.CharField(
        max_length=10,
        choices=STATUS_CHOICES,
        default=STATUS_LAUNCHED,
        verbose_name="Статус рассылки",
    )  # Статус
    sms = models.ForeignKey(
        Sms, on_delete=models.CASCADE, related_name="mail", verbose_name="Сообщение"
    )  # Сообщение (внешний ключ на модель «Сообщение»)
    client = models.ManyToManyField(
        Client, verbose_name="Получатель"
    )  # Получатели («многие ко многим», связь с моделью «Получатель»)
    is_active = models.BooleanField(default=True, verbose_name="активна")
    owner = models.ForeignKey(
        User,
        verbose_name="Владелец рассылки",
        help_text="укажите Владельца рассылки",
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
    )

    def __str__(self):
        return self.status

    class Meta:
        verbose_name = "Рассылка"
        verbose_name_plural = "Рассылки"
        ordering = [
            "status",
        ]
        permissions = [
            ("set_is_active", "set is active"),
        ]


class Send(models.Model):
    """Попытка рассылки"""

    STATUS_OK = "Успешно"
    STATUS_NOK = "Не успешно"

    STATUS_CHOICES = [
        (STATUS_OK, "статус: Успешно"),
        (STATUS_NOK, "статус: Не успешно"),
    ]

    data = models.DateTimeField(
        auto_now_add=True, verbose_name="Дата попытки рассылки"
    )  # Дата и время попытки
    sending_status = models.CharField(
        max_length=10,
        choices=STATUS_CHOICES,
        default=STATUS_OK,
        verbose_name="Статус попытки рассылки",
    )
    answer = models.TextField(
        null=True, blank=True, verbose_name="Ответ почтового сервера"
    )
    status = models.ForeignKey(
        Mail, on_delete=models.CASCADE, related_name="send", verbose_name="Статус рассылки"
    )  # внешний ключ на модель «Рассылка»
    owner = models.ForeignKey(
        User,
        verbose_name="Владелец рассылки",
        help_text="укажите Владельца рассылки",
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
    )

    def __str__(self):
        return self.sending_status

    class Meta:
        verbose_name = "Управление рассылкой"
        verbose_name_plural = "Управление рассылками"
        ordering = [
            "data",
            "sending_status",
        ]

# class Log(models.Model):
#     """Логирование попытки рассылки"""
#     mail = models.ForeignKey(Mail, on_delete=models.CASCADE, verbose_name='Рассылка')
#     last_time_mail = models.DateTimeField(auto_now=True, verbose_name='дата и время последней попытки')
#     status = models.CharField(max_length=50, verbose_name='Статус попытки')
#     response = models.TextField(verbose_name='Ответ сервера', null=True, blank=True)
#
#     def __str__(self):
#         return (f'Дата и время последней попытки: {self.last_time_mail}.'
#                 f' Статус попытки:{self.status}')
#
#     class Meta:
#         verbose_name = 'Лог'
#         verbose_name_plural = 'Логи'

message/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy


from message.forms import (
    ClientForm,
    SmsForm,
    MailForm,
    ClientModeratorForm,
    SmsModeratorForm,
    MailModeratorForm, SendForm,
)
from message.models import Client, Sms, Mail, Send
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
    TemplateView,
)

from message.services import get_clients_from_cash, get_send_from_cash


def base(request):
    """Основной шаблон"""
    return render(request, "base.html")


class Contacts(TemplateView):
    """Шаблон контакты"""

    template_name = "message/contacts.html"

    def contacts(request):
        if request.method == "POST":
            name = request.POST.get("name")  # получаем имя
            message = request.POST.get("message")  # получаем сообщение
            return HttpResponse(f"Спасибо, {name}! {message} Сообщение получено.")
        return render(request, "message/contacts.html")


class Message(TemplateView):
    """Страница ответа на отправленное сообщение"""

    template_name = "message/message.html"


class MainView(TemplateView):
    """Главная страница"""

    template_name = "message/main.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["mail_count"] = len(Mail.objects.all())
        context["active_count"] = len(Mail.objects.filter(status="Запущен"))
        context["unique_email"] = len(Client.objects.all())
        return context


class ClientListView(ListView):
    """Получатели рассылок - просмотр"""

    model = Client

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user == self.object.owner:
            self.object.save()
            return self.object
        raise PermissionDenied

    def get_queryset(self):
        return get_clients_from_cash()
# app_name/<model_name>_<action> т.е будет message/client_list.html


class ClientDetailView(DetailView, LoginRequiredMixin):
    """Получатель рассылки"""

    model = Client
    form_class = ClientForm

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user == self.object.owner:
            self.object.save()
            return self.object
        raise PermissionDenied


class ClientCreateView(CreateView, LoginRequiredMixin):
    """Получатель рассылки - создание"""

    model = Client
    form_class = ClientForm
    success_url = reverse_lazy("message:client_list")

    def form_valid(self, form):
        client = form.save()
        user = self.request.user
        client.owner = user
        client.save()

        return super().form_valid(form)


class ClientUpdateView(UpdateView, LoginRequiredMixin):
    """Получатель рассылки - обновление"""

    model = Client
    form_class = ClientForm
    success_url = reverse_lazy("message:client_list")

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user == self.object.owner:
            self.object.save()
            return self.object
        raise PermissionDenied

    def get_form_class(self):
        user = self.request.user
        if user.has_perm("message.can_unblocking_client") and user.has_perm(
            "message.can_disabling_mailings"
        ):
            return ClientModeratorForm
        return ClientForm


class ClientDeleteView(DeleteView):
    """Получатель рассылки - удаление"""

    model = Client
    success_url = reverse_lazy("message:client_list")

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user == self.object.owner:
            self.object.save()
            return self.object
        raise PermissionDenied


class SmsListView(ListView):
    """Сообщения - просмотр"""

    model = Sms


class SmsDetailView(DetailView, LoginRequiredMixin):
    """Просмотр выбранного сообщения"""

    model = Sms

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user == self.object.owner:
            self.object.save()
            return self.object
        raise PermissionDenied


class SmsCreateView(CreateView, LoginRequiredMixin):
    """Сообщения - создание"""

    model = Sms
    form_class = SmsForm
    success_url = reverse_lazy("message:sms_list")

    def form_valid(self, form):
        sms = form.save()
        user = self.request.user
        sms.owner = user
        sms.save()

        return super().form_valid(form)


class SmsUpdateView(UpdateView, LoginRequiredMixin):
    """Сообщения - обновление"""

    model = Sms
    form_class = SmsForm
    success_url = reverse_lazy("message:sms_list")

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user == self.object.owner:
            self.object.save()
            return self.object
        raise PermissionDenied

    def get_form_class(self):
        user = self.request.user
        if user.has_perm("message.can_unblocking_sms") and user.has_perm(
            "message.can_disabling_mailings"
        ):
            return SmsModeratorForm
        return SmsForm


class SmsDeleteView(DeleteView):
    """Сообщения - удаление"""

    model = Sms
    success_url = reverse_lazy("message:sms_list")

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user == self.object.owner:
            self.object.save()
            return self.object
        raise PermissionDenied


class MailListView(ListView):
    """Рассылка - просмотр"""

    model = Mail


class MailDetailView(DetailView, LoginRequiredMixin):
    """Просмотр выбранной рассылки"""

    model = Mail

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user == self.object.owner:
            self.object.save()
            return self.object
        raise PermissionDenied


class MailCreateView(CreateView, LoginRequiredMixin):
    """Рассылка - создание"""

    model = Mail
    form_class = MailForm
    success_url = reverse_lazy("message:mail_list")

    def form_valid(self, form):
        mail = form.save()
        user = self.request.user
        mail.owner = user
        mail.save()


class MailUpdateView(UpdateView, LoginRequiredMixin):
    """Рассылка - обновление"""

    model = Mail
    form_class = MailForm
    success_url = reverse_lazy("message:mail_list")

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user == self.object.owner:
            self.object.save()
            return self.object
        raise PermissionDenied

    def get_form_class(self):
        user = self.request.user
        if user.has_perm("message.can_unblocking_mailing") and user.has_perm(
            "message.can_disabling_mailings"
        ):
            return MailModeratorForm
        return MailForm


class MailDeleteView(DeleteView):
    """Рассылка - удаление"""

    model = Mail
    success_url = reverse_lazy("message:mail_list")

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user == self.object.owner:
            self.object.save()
            return self.object
        raise PermissionDenied


class SendListView(ListView, LoginRequiredMixin):
    model = Send

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user == self.object.owner:
            self.object.save()
            return self.object
        raise PermissionDenied

    def get_queryset(self):
        return get_send_from_cash()


class SendCreateView(LoginRequiredMixin, CreateView):
    model = Send
    form_class = SendForm

    def form_valid(self, form):
        send = form.save()
        user = self.request.user
        send.owner = user
        send.save()

message/templates/message/base.html
{% load static %}

<!doctype html>
<div lang="en" class="h-100" data-bs-theme="auto">
<head>
  <script src="/static/css/color-modes.js"></script>

{% include 'message/includes/ink_info.html' %}

{% block content %}
{% endblock %}



  <script src="/static/js/bootstrap.bundle.min.js"></script>

  </body>
{% include 'message/includes/ink_up.html' %}
</html>

message/templates/message/client_confirm_delete.html
{% extends 'message/base.html' %}

{% block content %}
<main class="flex-shrink-0">
  <div class="container">
    <h1 class="mt-5">Удаление клиента</h1>
    <p class="lead"></p>
    <div class="row mb-2">
    <div class="col-md-12">
        <div class="container">
    <div class="row">
        <div class="col">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <p class="card-text">Вы действительно хотите удалить клиента: "{{object.name}}"</p>
                    <div class="card-body">
                        {%  csrf_token %}
                    </div>
                    <div class="row mb-2">
                    <div class="col-md-12">
                        <button type="submit" class="btn btn-dark">Удалить</button>
                        <a class="btn btn-dark" href="{% url 'message:client_list' %}" role="button">Отменить</a>
                    </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
    </div>
    </div>
  </div>
</main>
{% endblock %}

message/templates/message/client_detail.html
{% extends 'message/base.html' %}

{% block content %}
<main class="flex-shrink-0">
  <div class="container">
    <h1 class="mt-5">Получатель рассылки</h1>
    <p class="lead"></p>
    <div class="row mb-2">
    <div class="col-md-12">
      <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <strong class="d-inline-block mb-2 text-primary-emphasis">Электронная почта: {{client.email}}</strong>
          <strong class="d-inline-block mb-2 text-primary-emphasis">ФИО: {{client.name}}</strong>
          <strong class="d-inline-block mb-2 text-primary-emphasis">Комментарии: {{client.comment}}</strong>
        </div>
        <div class="row mb-2">
        <div class="col-md-12">
          <a class="btn btn-dark" href="{% url 'message:client_list' %}" role="button">Назад</a>
        </div>
        </div>
      </div>
    </div>
    </div>
  </div>
</main>
{% endblock %}

message/templates/message/client_form.html
{% extends 'message/base.html' %}

{% block content %}
<main class="flex-shrink-0">
  <div class="container">
    <h1 class="mt-5">Получатель рассылки</h1>
    <p class="lead"></p>
    <div class="row mb-2">
    <div class="col-md-12">
    <div class="container">
        <div class="row">
            <div class="col">
                <form class="row" method="post" enctype="multipart/form-data">
                    <div class="card">
                        <div class="card-body">
                            {%  csrf_token %}
                            {{ form.as_p }}
                        </div>
                        <div class="row mb-2">
                        <div class="col-md-12">
                            <button type="submit" class="btn btn-dark">
                                {% if object %}
                                Сохранить
                                {% else %}
                                Создать
                                {% endif %}
                            </button>
                        </div>
                        </div>
                        <div class="row mb-2">
                        <div class="col-md-12">
                            <a class="btn btn-dark" href="{% url 'message:client_list' %}" role="button">Назад</a>
                        </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    </div>
    </div>
  </div>
</main>
{% endblock %}

message/templates/message/client_list.html
{% extends 'message/base.html' %}

{% block content %}
<main class="flex-shrink-0">
  <div class="container">
    <h1 class="mt-5">Управление клиентами</h1>
    <p class="lead">Вы можете добавлять, просматривать, редактировать и удалять получателей рассылки (клиентов)</p>
    <div class="container">
    {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="btn btn-dark" href="{% url 'message:client_create' %}" role="button">Создать получателя</a>
      </li>
    {% endif %}
    </div>

    <div class="row mb-2">
    <div class="col-md-12">

      {% for object in object_list %}

      <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <strong class="d-inline-block mb-2 text-primary-emphasis">Электронная почта: {{object.email}}</strong>
          <strong class="d-inline-block mb-2 text-primary-emphasis">ФИО: {{object.name}}</strong>
          <strong class="d-inline-block mb-2 text-primary-emphasis">Комментарии: {{object.comment}}</strong>

          {% if user.is_authenticated or user.is_superuser%}
          <strong class="d-inline-block mb-2 text-primary-emphasis">Пользователь: {{object.owner}}</strong>
          {% endif %}
        </div>
      </div>

        <div class="row mb-2">
        {% if user.is_authenticated%}
        <div class="col-md-12">
          <a class="btn btn-dark" href="{% url 'message:client_detail' object.pk %}" role="button">Посмотреть</a>
          <a class="btn btn-dark" href="{% url 'message:client_update' object.pk %}" role="button">Редактировать</a>

          {% if perms.message.delete_client or client.owner == object.user.email %}
            <a class="btn btn-dark" href="{% url 'message:client_delete' object.pk %}" role="button">Удалить</a>
          {% endif %}

        </div>
        {% endif %}
        </div>

      {% endfor %}

    </div>
    </div>
  </div>
</main>
{% endblock %}

message/templates/message/contacts.html
{% extends 'message/base.html' %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>Россия</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>1650000000</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Казань, Чистопольская ул., д. 24</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="+7(ХХХ)ХХХ ХХ ХХ" required>
                        </div>
                        <div class="mb-3">
                            <label for="email">Электронная почта</label>
                            <input type="text" name="email" class="form-control" id="email" placeholder="email@email.ru" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Введите сообщение" required></textarea>
                        </div>
                        <a class="btn btn-dark" href="{% url 'message:message' %}" role="button">Отправить</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

message/templates/message/message.html
{% extends 'message/base.html' %}

{% block content %}

<div class="container">
    <h1 class="mt-5">Главная страница</h1>
    <p class="lead"></p>
  </div>
  <div class="row mb-2">
    <div class="col-md-12">

        <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
            <div class="row">
                <div class="col-6">
                    <form class="row" method="post" enctype="multipart/form-data">
                        <div class="card">
                            <p class="card-text">Ваше сообщение получено!</p>
                            <div class="card-body"></div>
                            <div class="row mb-2">
                            <div class="col-md-12">
                                <a class="btn btn-dark" href="{% url 'message:main' %}" role="button">Главная</a>
                                <a class="btn btn-dark" href="{% url 'message:contacts' %}" role="button">Контакты</a>
                            </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
  </div>
</div>
{% endblock %}

message/templates/message/send_form.html
{% extends 'message/base.html' %}

{% block content %}
<main class="flex-shrink-0">
  <div class="container">
    <h1 class="mt-5">Попытка рассылки</h1>
    <p class="lead"></p>
    <div class="row mb-2">
    <div class="col-md-12">
    <div class="container">
        <div class="row">
            <div class="col">
                <form class="row" method="post" enctype="multipart/form-data">
                    <div class="card">
                        <div class="card-body">
                            {%  csrf_token %}
                            {{ form.as_p }}
                        </div>
                        <div class="row mb-2">
                        <div class="col-md-12">
                            <button type="submit" class="btn btn-dark">
                                {% if object %}
                                Сохранить
                                {% else %}
                                Создать
                                {% endif %}
                            </button>
                        </div>
                        </div>
                        <div class="row mb-2">
                        <div class="col-md-12">
                            <a class="btn btn-dark" href="{% url 'message:send_list' %}" role="button">Назад</a>
                        </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    </div>
    </div>
  </div>
</main>
{% endblock %}

message/templates/message/send_list.html
{% extends 'message/base.html' %}

{% block content %}
<main class="flex-shrink-0">
  <div class="container">
    <h1 class="mt-5">Попытка рассылки</h1>
    <p class="lead">Запись о каждой попытке отправки сообщения по рассылке</p>

    <div class="container">
    {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="btn btn-dark" href="{% url 'message:send_create' %}" role="button">Создать попытку рассылку</a>
      </li>
    {% endif %}
    </div>

    <div class="row mb-2">
    <div class="col-md-12">
    {% for object in object_list %}
      <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <strong class="d-inline-block mb-2 text-primary-emphasis">Дата попытки рассылки: {{object.data |date:"d M Y P"}}</strong>
          <strong class="d-inline-block mb-2 text-danger-emphasis">Статус попытки рассылки: {{ object.sending_status | upper }}</strong>
          <strong class="d-inline-block mb-2 text-primary-emphasis">Ответ почтового сервера: {{ object.answer }}</strong>
          <strong class="d-inline-block mb-2 text-primary-emphasis">Статус рассылки: {{ object.status }}</strong>
          <strong class="d-inline-block mb-2 text-primary-emphasis">Владелец рассылки: {{ object.owner }}</strong>
        </div>
      </div>
    {% endfor %}
    </div>
    </div>

    <div class="row mb-2">
    <div class="col-md-2">
      <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <a class="btn btn-dark" href="{% url 'message:main' %}" role="button">Назад</a>
        </div>
      </div>
    </div>
    </div>

  </div>
</main>
{% endblock %}